stop_words = ['began', 'go', 'small', 'somebody', 'long', 'smaller', 'kind', 'know', 'knows', 'wells', 'every', 'puts', 'made', 'amid', 'high', 'also', 'men', 'fully', 'over', 'both', 'become', 'wanting', 'being', 'his', 'taken', 'therefore', 'either', 'now', 'everybody', 'general', 'the', 'number', 'places', 'of', 'rather', 'place', 'seem', 'gave', 'onto', 'could', 'regarding', 'pointed', 'perhaps', 'felt', 'way', 'not', 'younger', 'within', 'that', 'turned', 'each', 'ordering', 'opened', 'last', 'evenly', 'below', 'any', 'presenting', 'asks', 'around', 'goods', 'ever', 'others', 'along', 'or', 'furthering', 'yet', 'longest', 'downed', 'shall', 'latest', 'need', 'more', 'different', 'against', 'anything', 'next', 'member', 'took', 'until', 'better', 'itself', 'you', 'new', 'mrs', 'newer', 'thoughts', 'older', 'put', 'presents', 'besides', 'certain', 'while', 'second', 'it', 'needed', 'turns', 'everything', 'face', 'there', 'me', 'done', 'another', 'despite', 'us', 'be', 'versus', 'three', 'always', 'today', 'away', 'let', 'such', 'seeming', 'clear', 'from', 'often', 'case', 'becomes', 'round', 'nobody', 'between', 'by', 'minus', 'how', 'gives', 'was', 'towards', 'show', 'generally', 'would', 'behind', 'even', 'same', 'noone', 'numbers', 'used', 'furthered', 'big', 'everyone', 'nothing', 'them', 'with', 'anti', 'does', 'past', 'aboard', 'many', 'above', 'less', 'sure', 'greatest', 'here', 'interesting', 'asked', 'faces', 'herself', 'mostly', 'out', 'part', 'right', 'interested', 'do', 'keep', 'early', 'considering', 'seconds', 'asking', 'anybody', 'ask', 'so', 'opens', 'interests', 'just', 'thus', 'whose', 'state', 'states', 'backing', 'has', 'among', 'area', 'showed', 'plus', 'everywhere', 'never', 'are', 'quite', 'no', 'once', 'excepting', 'excluding', 'may', 'says', 'least', 'see', 'sides', 'known', 'where', 'fact', 'almost', 'going', 'still', 'differently', 'might', 'since', 'downs', 'came', 'those', 'is', 'two', 'ends', 'seems',
              'seemed', 'inside', 'whether', 'he', 'very', 'ways', 'off', 'cannot', 'had', 'beings', 'given', 'worked', 'together', 'which', 'differ', 'certainly', 'shows', 'like', 'anywhere', 'making', 'find', 'give', 'only', 'thought', 'been', 'again', 'her', 'what', 'an', 'became', 'too', 'following', 'greater', 'needing', 'want', 'newest', 'get', 'lets', 'four', 'during', 'necessary', 'year', 'parting', 'save', 'our', 'full', 'then', 'non', 'did', 'before', 'uses', 'members', 'its', 'ending', 'presented', 'into', 'point', 'group', 'turn', 'really', 'will', 'something', 'alone', 'interest', 'under', 'without', 'longer', 'take', 'nowhere', 'these', 'cases', 'my', 'upon', 'smallest', 'far', 'ordered', 'good', 'years', 'groups', 'possible', 'opposite', 'have', 'said', 'why', 'back', 'parts', 'ended', 'when', 'thinks', 'finds', 'higher', 'to', 'much', 'best', 'grouped', 'however', 'young', 'except', 'him', 'sees', 'their', 'after', 'were', 'beyond', 'old', 'orders', 'mr', 'areas', 'first', 'yours', 'youngest', 'come', 'although', 'furthers', 'already', 'we', 'having', 'side', 'further', 'downing', 'down', 'through', 'for', 'most', 'underneath', 'himself', 'someone', 'grouping', 'though', 'work', 'at', 'order', 'whole', 'across', 'but', 'as', 'use', 'than', 'think', 'works', 'if', 'up', 'rooms', 'room', 'large', 'who', 'wanted', 'went', 'pointing', 'keeps', 'on', 'per', 'problem', 'showing', 'backs', 'near', 'toward', 'about', 'needs', 'man', 'enough', 'they', 'oldest', 'saw', 'wants', 'other', 'concerning', 'thing', 'anyone', 'this', 'because', 'via', 'parted', 'in', 'must', 'few', 'one', 'end', 'likely', 'things', 'highest', 'largely', 'important', 'beneath', 'make', 'turning', 'backed', 'all', 'beside', 'open', 'well', 'outside', 'somewhere', 'opening', 'clearly', 'myself', 'should', 'your', 'great', 'unlike', 'working', 'can', 'points', 'got', 'some', 'several', 'later', 'and', 'knew', 'problems', 'say', 'she', 'facts', 'present', 'gets']
prep = ['aboard', 'about', 'above', 'across', 'after', 'against', 'along', 'amid', 'among', 'anti', 'around', 'as', 'at', 'before', 'behind', 'below', 'beneath', 'beside', 'besides', 'between', 'beyond', 'but', 'by', 'concerning', 'considering', 'despite', 'down', 'during', 'except', 'excepting', 'excluding', 'following', 'for',
        'from', 'in', 'inside', 'into', 'like', 'minus', 'near', 'of', 'off', 'on', 'onto', 'opposite', 'outside', 'over', 'past', 'per', 'plus', 'regarding', 'round', 'save', 'since', 'than', 'through', 'to', 'toward', 'towards', 'under', 'underneath', 'unlike', 'until', 'up', 'upon', 'versus', 'via', 'with', 'within', 'without', ]
a = input("Enter a sentence: ").lower().split()
b, c = (list() for i in range(2))
for x in a:
    if x in stop_words:
        b.append(x)
print(f"The list of stop-words in the input is: {b}")
print(f"The number of prepositions in the input are: {len(b)}")
for x in a:
    if x in prep:
        c.append(x)
print(f"The list of prepositions in the input is: {c}")
print(f"The number of prepositions in the input are: {len(c)}")
